name: Build, Test & Deploy ASP.Net Core app to Azure Web App - thamco-product-catalogue-api

on:
  push: {}
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

env:
  DOTNET_VERSION: 6.0.x
  BUILD_CONFIGURATION: Release
  PROJECT_PATH: ./ThreeAmigos.Services.ProductCatalogue.API
  PUBLISH_PATH: ./myapi
  TESTRESULTS_PATH: ./unit-test-results

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: |
          dotnet test \
            --configuration $BUILD_CONFIGURATION \
            --no-build \
            --logger trx \
            --results-directory $TESTRESULTS_PATH
            
      - name: Store test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{ env.TESTRESULTS_PATH }}
        if: ${{ always() }} 

      - name: dotnet publish
        run: |
          dotnet publish $PROJECT_PATH \
            --configuration $BUILD_CONFIGURATION \
            --no-build \
            --output $PUBLISH_PATH

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ env.PUBLISH_PATH }}

  Deploy-Test:
    runs-on: ubuntu-latest
    needs: Build-And-Test
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ${{ env.PUBLISH_PATH }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'thamco-product-catalogue-api-test'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_PATH }}  

  Deploy-Production:
    runs-on: ubuntu-latest
    needs: Deploy-Test
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ${{ env.PUBLISH_PATH }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'thamco-product-catalogue-api-live'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_PATH }}  
